# Generated by Django 4.1.3 on 2022-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchreceipt',
            name='branch',
            field=models.CharField(blank=True, default='المركز الرئيسي', help_text=' الفرع', max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='catchreceipt',
            name='payment_method',
            field=models.CharField(blank=True, default='نقداً', help_text=' طريقة الدفع', max_length=225, null=True),
        ),
    ]
