# Generated by Django 4.1.2 on 2022-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_catchreceipt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchreceipt',
            name='total_amount',
            field=models.CharField(blank=True, default='0', help_text='المجموع', max_length=225, null=True),
        ),
    ]
