# Generated by Django 4.1.2 on 2022-10-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmodel',
            name='source',
            field=models.CharField(default='', help_text=' المصدر', max_length=225),
        ),
    ]
