# Generated by Django 3.1.3 on 2022-10-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20221011_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddrivermodel',
            name='Sequence_image',
        ),
        migrations.RemoveField(
            model_name='adddrivermodel',
            name='car_picture',
        ),
        migrations.RemoveField(
            model_name='adddrivermodel',
            name='license_photo',
        ),
    ]
