# Generated by Django 3.1.3 on 2022-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='اسم الشركة', max_length=225)),
                ('company_city', models.CharField(help_text='مقر الشركة', max_length=225)),
                ('charging_area', models.CharField(help_text='منطقة الشحن ', max_length=225)),
            ],
        ),
    ]
